# TODO 1. h2(mem-db) 설정을 추가한다.

server:
  port: 8080
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

test:
  str: 문자열
  ary: [ 1, 10, 100 ]

---
### Local 운영환경 ###
spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        format_sql: true  # JPA 쿼리 보여주는 설정
        database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
logging: # JPA 쿼리 보여주는 설정
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE