server:
  port: 8080
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none

# TODO 2. yml 파일에 변수들을 입력한다
test:
  str: 문자열
  ary: [ 1, 10, 100 ]

---
### Local 운영환경 ###
spring:
  config:
    activate:
      on-profile: local